#### Apache ####
---
apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'apache-test' # This is used by HAproxy as backend identification.
  labels:
    url: 'xpto.test.com' # url and domain expected by HAproxy in frontend
    haproxy: 'true' # Set to true so the service is add in haproxy.cfg.
spec:
  type: 'NodePort'
  ports:
  - port: 80
    name: 'http'
  selector:
    app: 'http'