---
apiVersion: 'v1'
kind: 'Pod'
metadata:
  name: 'metadata-name'
  labels:
    app: 'app-name'
spec:
  containers:
  - image: 'php:5.6.31-fpm-alpine3.4'
    name: 'php-fpm'
    ports:
      - containerPort: 9000
        name: 'php-fpm-port'
        protocol: 'TCP'
---
apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'php-fpm' # This is the name used as backend identification.
  labels:
    haproxy: true
spec:
  ports:
  type: NodePort
  - port: 9000
    name: 'php-fpm'
  selector:
    app: 'app-name'